import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import Providers from "../../lib/providers";
import { Header } from "@/components/header";
import { Footer } from "@/components/footer";
import { NavigationEvents } from "@/components/navigation-events";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "HackNU 24",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
      }}
    >
      <html lang="en">
        <body className={inter.className}>
          <Providers>
            <main className="relative min-h-screen bg-background pb-[72px] antialiased sm:pb-[80px]">
              <Header />
              {children}
              <Suspense fallback={null}>
                <NavigationEvents />
              </Suspense>
              <Footer />
            </main>
          </Providers>
        </body>
      </html>
    </ClerkProvider>
  );
}
